learn-python/ex51/app/__init__.py
from flask import Flask
from os.path import join
from os import makedirs
from .views.hello import bp as hello_bp

def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='DEV',
        DATABASE=join(app.instance_path, 'app.sqlite')
    )

    if test_config is None:
        app.config.from_pyfile('config.py', silent=True)
    else:
        app.config.from_mapping(test_config)

    try:
        makedirs(app.instance_path)
    except OSError:
        pass
    
    app.register_blueprint(hello_bp)
    
    return app

learn-python/ex51/app/views/hello.py
from flask import (
    Blueprint, request, render_template, redirect, url_for
)

bp = Blueprint('hello', __name__, url_prefix='/hello')

@bp.route('/')
@bp.route('/q?greet=<greet>&name=<name>')
def index(greet='Hello' , name='Nobody'):
    return render_template('/hello/index.html', greet=greet, name=name)

@bp.route('/form/', methods=('GET', 'POST'))
def form():
    if request.method == 'POST':
        greet = request.form['greet']
        name = request.form['name']
        if not greet:
            greet = "Hello"
        if not name:
            name = "Nobody"
        return redirect(url_for('hello.index', greet=greet, name=name))
        
    return render_template('hello/form.html')

learn-python/ex51/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - Ex51</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <nav>
        <h1>Ex 51</h1>
    </nav>
    <section class="content">
        <header>
            {% block header %}{% endblock %}
        </header>
        {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
        {% endfor %}
        {% block content %}{% endblock %}
    </section>
</body>
</html>

learn-python/ex51/app/templates/hello/form.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Fill Out This Form{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        <ul>
            <li>
                <label for="greet">
                    A Greeting:
                    <input type="text" id="greet" name="greet" >
                </label>
            </li>
            <li>
                <label for="name">
                    Your Name:
                    <input type="text" id="name" name="name" >
                </label>
            </li>
            <li>
                <input type="submit" value="Submit">
            </li>
        </ul>
    </form>
{% endblock %}

learn-python/ex51/app/templates/hello/index.html
{% extends 'base.html' %}

{% block header %}
    <h1>Greetings from Zod</h1>
{% endblock %}

{% block content %}
    <h1>{{ greet.title() }}, {{ name.title() }}</h1>
    <a href="{{ url_for('hello.form') }}">Go to form</a>
{% endblock %}

learn-python/ex51/app/templates/hello_form.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Fill Out This Form{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        <ul>
            <li>
                <label for="greet">
                    A Greeting:
                    <input type="text" id="greet" name="greet" >
                </label>
            </li>
            <li>
                <label for="name">
                    Your Name:
                    <input type="text" id="name" name="name" >
                </label>
            </li>
            <li>
                <input type="submit" value="Submit">
            </li>
        </ul>
    </form>
{% endblock %}